Paparazzi UAS: sw/airborne/modules/datalink/gec_dl.c File Reference
gec_dl.c File Reference
#include "gec_dl.h"
#include "modules/datalink/gec/gec.h"
#include "subsystems/datalink/datalink.h"
#include "pprzlink/messages.h"
#include <string.h>
#include "subsystems/datalink/telemetry.h"
Functions
void gec_encapsulate_and_send_msg (struct pprzlink_msg *msg, long fd)
Encapsulate message data (CRYPTO_BYTE .
static void gec_transport_init (struct gec_transport *t)
static void send_secure_link_info (struct transport_tx *trans, struct link_device *dev)
uint32_t gec_bytes_to_counter (uint8_t *bytes)
Convert from network byte order (big endian) to the machine byte order.
void gec_counter_to_bytes (uint32_t n, uint8_t *bytes)
Convert counter to bytes in network byte order.
static struct gec_transport * get_trans (struct pprzlink_msg *msg)
Helper function to get the relevant transport struct.
static void insert_byte (struct gec_transport *t, const uint8_t byte)
Simply insert byte to the message buffer.
void gec_add_to_whitelist (struct gec_whitelist *whitelist, uint8_t id)
bool gec_is_in_the_whitelist (struct gec_whitelist *whitelist, uint8_t id)
static void put_bytes (struct pprzlink_msg *msg, long fd, enum TransportDataType type, enum TransportDataFormat format, const void *bytes, uint16_t len)
Simply put bytes in the message buffer.
static void put_named_byte (struct pprzlink_msg *msg, long fd, enum TransportDataType type, enum TransportDataFormat format, uint8_t byte, const char *name)
static uint8_t size_of (struct pprzlink_msg *msg, uint8_t len)
Return the length of a regular pprzlink message (PPRZ_STX .
static void start_message (struct pprzlink_msg *msg, long fd, uint8_t payload_len)
Just reset the message data.
static void overrun (struct pprzlink_msg *msg)
Report to the underlying transport.
static void count_bytes (struct pprzlink_msg *msg, uint8_t bytes)
Call the underlying transport.
static int check_available_space (struct pprzlink_msg *msg, long *fd, uint16_t bytes)
Check that there is enought space in the buffer.
void gec_dl_init (void)
Init function.
static void end_message (struct pprzlink_msg *msg, long fd)
Get bytes from the message buffer (SENDER_ID .
bool gec_encrypt_message (uint8_t *buf, uint8_t *payload_len)
Attempts message encryption Adds crypto_byte, counter and tag Assumes that the first two bytes of 'payload' are source_ID and dest_ID and these two bytes will be authenticated Returns encrypted pprzlink 2.0 message (crypto_byte .
bool gec_decrypt_message (uint8_t *buf, volatile uint8_t *payload_len)
Attemp message decryption If a message is unencrypted, pass it through only if the MSG_ID is in the whitelist Returns Pprzlink 2.0 message bytes (source_ID .
void gec_dl_event (void)
Parse incoming message bytes (PPRZ_STX..CHCKSUM B) and returns a new decrypted message if it is available.
void gec_process_msg1 (uint8_t *buf)
NOTE: for RESPONDER party only Process incoming message (expected MSG1) if the right (KEY_EXCHANGE) message received with the right data (P_AE) and the right P_AE.len=PPRZ_KEY_LEN, the internal state of Sts gets updated (key derivation etc), and msg2 is prepared to be sent.
bool gec_process_msg3 (uint8_t *buf)
Process incoming message (expected MSG3) if the right (KEY_EXCHANGE) message received with the right data (SIG) and the right SIG.len=PPRZ_SIGN_LEN, and the signature is verified, Ok() is returned.
Variables
struct gec_transport gec_tp
PPRZ transport structure.
Function Documentation
static int check_available_space (struct pprzlink_msg * msg, long * fd, uint16_t bytes) static
Check that there is enought space in the buffer.
Two cases: if CRYPTO_OK: return the check_available_space from the underlying transport else: return zero, to avoid race conditions over the message buffer (no messages are being sent before the key exchange)
Definition at line 227 of file gec_dl.c.
References CRYPTO_OK, get_trans(), gec_transport::pprz_tp, gec_sts_ctx::protocol_stage, and gec_transport::sts.
Referenced by gec_transport_init().
static void count_bytes (struct pprzlink_msg * msg, uint8_t bytes) static
Call the underlying transport.
Definition at line 213 of file gec_dl.c.
References get_trans(), and gec_transport::pprz_tp.
Referenced by gec_transport_init().
static void end_message (struct pprzlink_msg * msg, long fd) static
Get bytes from the message buffer (SENDER_ID .
. MSG_PAYLOAD) Add crypto byte Attempt encryption If succesfull, add counter, auth, ciphertext and tag (CRYPTO_BYTE .. TAG) and wrap in pprz transport (PPRZ_STX .. CHECKSUM)
Definition at line 264 of file gec_dl.c.
References CRYPTO_OK, gec_encapsulate_and_send_msg(), gec_encrypt_message(), gec_tp, get_trans(), PPRZ_MUTEX_UNLOCK, gec_sts_ctx::protocol_stage, gec_transport::sts, gec_transport::tx_msg, and gec_transport::tx_msg_idx.
Referenced by gec_transport_init().
void gec_add_to_whitelist (struct gec_whitelist * whitelist, uint8_t id)
Definition at line 130 of file gec_dl.c.
References gec_whitelist::idx, gec_whitelist::init, gec_whitelist::whitelist, and WHITELIST_LEN.
Referenced by gec_transport_init().
uint32_t gec_bytes_to_counter (uint8_t * bytes)
Convert from network byte order (big endian) to the machine byte order.
Definition at line 62 of file gec_dl.c.
Referenced by gec_decrypt_message().
void gec_counter_to_bytes (uint32_t n, uint8_t * bytes)
Convert counter to bytes in network byte order.
Definition at line 87 of file gec_dl.c.
Referenced by gec_encrypt_message().
bool gec_decrypt_message (uint8_t * buf, volatile uint8_t * payload_len)
Attemp message decryption If a message is unencrypted, pass it through only if the MSG_ID is in the whitelist Returns Pprzlink 2.0 message bytes (source_ID .
. msg payload)
Input: expects (CRYPTO_BYTE .. MSG_DATA .. optional TAG) Output: returns stripped message (SENDER_ID .. MSG_PAYLOAD)
Definition at line 383 of file gec_dl.c.
References counter, gec_sym_key::counter, gec_sts_ctx::decrypt_err, gec_bytes_to_counter(), gec_is_in_the_whitelist(), gec_tp, gec_sym_key::key, gec_sym_key::nonce, PPRZ_AUTH_IDX, PPRZ_AUTH_LEN, PPRZ_CIPH_IDX, PPRZ_CNTR_IDX, PPRZ_CRYPTO_OVERHEAD, PPRZ_ENCRYPTED_MSG_MIN_LEN, PPRZ_GEC_IDX, PPRZ_MAC_LEN, PPRZ_MSG_TYPE_ENCRYPTED, PPRZ_MSG_TYPE_PLAINTEXT, PPRZ_PLAINTEXT_MSG_ID_IDX, PPRZ_PLAINTEXT_MSG_MIN_LEN, gec_sym_key::ready, gec_sts_ctx::rx_counter_err, gec_sts_ctx::rx_sym_key, gec_transport::sts, and gec_transport::whitelist.
Referenced by gec_dl_event().
void gec_dl_event (void)
Parse incoming message bytes (PPRZ_STX..CHCKSUM B) and returns a new decrypted message if it is available.
Datalink Event.
While the status != Crypto_OK no message is returned, and all logic is handled internally. Returned message has format of Pprzlink 2.0 ```ignore payload[0] source SENDER_ID payload[1] destination ID payload[2] class/component payload[3] MSG_ID payload[4-end] MSG_PAYLOAD ``` and can be directly processed by a parser
NOTE: the KEY_EXCHANGE messages are whitelisted and thus pass through the "decryption" even if they are in plaintext and after the key exchange is established. This is not a problem, because we don't act on them. It would be good to limit "sending" them from other processes, but for now lets assume nobody will want to send this message.
In the future, the KEY_EXCHANGE messages will be handled in firmware_parse_datalink_msgs() and act upon accordingly (i.e. the key renegotiation will be possible). For now, I am keeping this note here as a reminder.
Definition at line 479 of file gec_dl.c.
References CRYPTO_OK, DatalinkFillDlBuffer, dl_buffer, dl_msg_available, DlCheckAndParse(), DOWNLINK_DEVICE, gec_decrypt_message(), gec_process_msg1(), gec_process_msg3(), gec_tp, LED_ON, gec_transport::pprz_tp, gec_sts_ctx::protocol_stage, gec_transport::sts, gec_transport::trans_rx, gec_transport::trans_tx, WAIT_MSG1, and WAIT_MSG3.
void gec_dl_init (void)
Init function.
Definition at line 237 of file gec_dl.c.
References DefaultPeriodic, gec_sts_init(), gec_tp, gec_transport_init(), LED_OFF, gec_transport::pprz_tp, register_periodic_telemetry(), send_secure_link_info(), and gec_transport::sts.
void gec_encapsulate_and_send_msg (struct pprzlink_msg * msg, long fd)
Encapsulate message data (CRYPTO_BYTE .
. MSG_PAYLOAD .. TAG) with pprzlink header and checksum (PPRZ_STX .. CHECKSUM). and send message
Definition at line 306 of file gec_dl.c.
References get_trans(), gec_transport::pprz_tp, gec_transport::tx_msg, and gec_transport::tx_msg_idx.
Referenced by end_message(), and gec_process_msg1().
bool gec_encrypt_message (uint8_t * buf, uint8_t * payload_len)
Attempts message encryption Adds crypto_byte, counter and tag Assumes that the first two bytes of 'payload' are source_ID and dest_ID and these two bytes will be authenticated Returns encrypted pprzlink 2.0 message (crypto_byte .
. tag) in the same buffer as was the incoming message
Definition at line 323 of file gec_dl.c.
References counter, gec_sym_key::counter, gec_sts_ctx::encrypt_err, gec_counter_to_bytes(), gec_tp, gec_sym_key::key, gec_sym_key::nonce, PPRZ_AUTH_IDX, PPRZ_AUTH_LEN, PPRZ_CIPH_IDX, PPRZ_CNTR_IDX, PPRZ_CRYPTO_OVERHEAD, PPRZ_GEC_IDX, PPRZ_MAC_LEN, PPRZ_MSG_TYPE_ENCRYPTED, PPRZ_V2_MSG_ID, gec_sym_key::ready, gec_transport::sts, and gec_sts_ctx::tx_sym_key.
Referenced by end_message().
bool gec_is_in_the_whitelist (struct gec_whitelist * whitelist, uint8_t id)
Definition at line 144 of file gec_dl.c.
References gec_whitelist::idx, gec_whitelist::init, and gec_whitelist::whitelist.
Referenced by gec_decrypt_message().
void gec_process_msg1 (uint8_t * buf)
NOTE: for RESPONDER party only Process incoming message (expected MSG1) if the right (KEY_EXCHANGE) message received with the right data (P_AE) and the right P_AE.len=PPRZ_KEY_LEN, the internal state of Sts gets updated (key derivation etc), and msg2 is prepared to be sent.
Input: decrypted message (source_ID .. msg payload) If all good, it sends response message
Definition at line 544 of file gec_dl.c.
References DOWNLINK_DEVICE, gec_derive_key_material(), gec_encapsulate_and_send_msg(), gec_generate_ephemeral_keys(), gec_tp, gec_sym_key::key, gec_sts_ctx::last_error, MSG1_ENCRYPT_ERROR, gec_sts_ctx::my_private_ephemeral, gec_sts_ctx::my_private_key, gec_sym_key::nonce, P_AE, P_BE, PPRZ_GEC_IDX, PPRZ_KEY_LEN, PPRZ_MAC_LEN, PPRZ_MSG_TYPE_PLAINTEXT, PPRZ_SIGN_LEN, gec_transport::pprz_tp, gec_privkey::priv, gec_sts_ctx::protocol_stage, gec_privkey::pub, gec_pubkey::pub, gec_privkey::ready, gec_pubkey::ready, gec_transport::sts, gec_sts_ctx::their_public_ephemeral, gec_transport::tx_msg, gec_transport::tx_msg_idx, gec_sts_ctx::tx_sym_key, UNEXPECTED_MSG_DATA_ERROR, UNEXPECTED_MSG_ERROR, UNEXPECTED_MSG_TYPE_ERROR, and WAIT_MSG3.
Referenced by gec_dl_event().
bool gec_process_msg3 (uint8_t * buf)
Process incoming message (expected MSG3) if the right (KEY_EXCHANGE) message received with the right data (SIG) and the right SIG.len=PPRZ_SIGN_LEN, and the signature is verified, Ok() is returned.
Input: decrypted message (source_ID .. msg payload) Returns true if this party is ready for communication
Definition at line 664 of file gec_dl.c.
References gec_tp, gec_sym_key::key, gec_sts_ctx::last_error, MSG3_DECRYPT_ERROR, MSG3_SIGNVERIFY_ERROR, gec_sts_ctx::my_private_ephemeral, gec_sym_key::nonce, PPRZ_KEY_LEN, PPRZ_MAC_LEN, PPRZ_SIGN_LEN, gec_privkey::pub, gec_pubkey::pub, gec_sts_ctx::rx_sym_key, SIG, sign, gec_transport::sts, gec_sts_ctx::their_public_ephemeral, gec_sts_ctx::their_public_key, UNEXPECTED_MSG_DATA_ERROR, UNEXPECTED_MSG_ERROR, and UNEXPECTED_MSG_TYPE_ERROR.
Referenced by gec_dl_event().
static void gec_transport_init (struct gec_transport * t) static
Definition at line 281 of file gec_dl.c.
References check_available_space(), count_bytes(), end_message(), gec_add_to_whitelist(), KEY_EXCHANGE_MSG_ID_GCS, KEY_EXCHANGE_MSG_ID_UAV, overrun(), PPRZ_MUTEX_INIT, put_bytes(), put_named_byte(), size_of(), start_message(), gec_transport::trans_rx, gec_transport::trans_tx, and gec_transport::whitelist.
Referenced by gec_dl_init().
static struct gec_transport* get_trans (struct pprzlink_msg * msg) static
Helper function to get the relevant transport struct.
Definition at line 115 of file gec_dl.c.
Referenced by check_available_space(), count_bytes(), end_message(), gec_encapsulate_and_send_msg(), overrun(), put_bytes(), put_named_byte(), size_of(), and start_message().
static void insert_byte (struct gec_transport * t, const uint8_t byte) inline static
Simply insert byte to the message buffer.
Definition at line 123 of file gec_dl.c.
References byte, gec_transport::tx_msg, and gec_transport::tx_msg_idx.
Referenced by put_bytes(), and put_named_byte().
static void overrun (struct pprzlink_msg * msg) static
Report to the underlying transport.
Definition at line 205 of file gec_dl.c.
References get_trans(), and gec_transport::pprz_tp.
Referenced by gec_transport_init().
static void put_bytes (struct pprzlink_msg * msg, long fd, enum TransportDataType type, enum TransportDataFormat format, const void * bytes, uint16_t len) static
Simply put bytes in the message buffer.
Definition at line 159 of file gec_dl.c.
References get_trans(), and insert_byte().
Referenced by gec_transport_init().
static void put_named_byte (struct pprzlink_msg * msg, long fd, enum TransportDataType type, enum TransportDataFormat format, uint8_t byte, const char * name) static
Definition at line 171 of file gec_dl.c.
References get_trans(), and insert_byte().
Referenced by gec_transport_init().
static void send_secure_link_info (struct transport_tx * trans, struct link_device * dev) static
Definition at line 48 of file gec_dl.c.
References gec_sts_ctx::decrypt_err, gec_sts_ctx::encrypt_err, gec_tp, gec_sts_ctx::last_error, gec_sts_ctx::protocol_stage, gec_sts_ctx::rx_counter_err, and gec_transport::sts.
Referenced by gec_dl_init().
static uint8_t size_of (struct pprzlink_msg * msg, uint8_t len) static
Return the length of a regular pprzlink message (PPRZ_STX .
. CHECKSUM) and add CRYPTO_OVERHEAD(20) + crypto byte(1)
Definition at line 184 of file gec_dl.c.
References get_trans(), PPRZ_CRYPTO_OVERHEAD, and gec_transport::pprz_tp.
Referenced by gec_transport_init().
static void start_message (struct pprzlink_msg * msg, long fd, uint8_t payload_len) static
Just reset the message data.
Definition at line 193 of file gec_dl.c.
References get_trans(), PPRZ_MUTEX_LOCK, gec_transport::tx_msg, and gec_transport::tx_msg_idx.
Referenced by gec_transport_init().
Variable Documentation
struct gec_transport gec_tp
PPRZ transport structure.
Definition at line 43 of file gec_dl.c.
Referenced by end_message(), gec_decrypt_message(), gec_dl_event(), gec_dl_init(), gec_encrypt_message(), gec_process_msg1(), gec_process_msg3(), and send_secure_link_info().