Paparazzi UAS: sw/airborne/modules/orange_avoider/orange_avoider.h File Reference
orange_avoider.h File Reference
#include <inttypes.h>
#include "math/pprz_geodetic_int.h"
Functions
void orange_avoider_init (void)
void orange_avoider_periodic (void)
uint8_t moveWaypointForward (uint8_t waypoint, float distanceMeters)
uint8_t moveWaypoint (uint8_t waypoint, struct EnuCoor_i *new_coor)
uint8_t increase_nav_heading (int32_t *heading, float incrementDegrees)
uint8_t chooseRandomIncrementAvoidance (void)
Variables
uint8_t safeToGoForwards
float incrementForAvoidance
uint16_t trajectoryConfidence
Detailed Description
Author
Roland Meertens Example on how to use the colours detected to avoid orange pole in the cyberzoo
Definition in file orange_avoider.h.
Function Documentation
uint8_t chooseRandomIncrementAvoidance (void)
Definition at line 169 of file orange_avoider.c.
References incrementForAvoidance, and VERBOSE_PRINT.
Referenced by orange_avoider_init(), and orange_avoider_periodic().
uint8_t increase_nav_heading (int32_t * heading, float incrementDegrees)
Definition at line 114 of file orange_avoider.c.
References ANGLE_BFP_OF_REAL, ANGLE_FLOAT_OF_BFP, INT32_ANGLE_NORMALIZE, Int32Eulers::psi, stateGetNedToBodyEulers_i(), and VERBOSE_PRINT.
Referenced by orange_avoider_periodic().
uint8_t moveWaypoint (uint8_t waypoint, struct EnuCoor_i * new_coor)
Definition at line 147 of file orange_avoider.c.
References POS_FLOAT_OF_BFP, VERBOSE_PRINT, waypoint_set_xy_i(), EnuCoor_i::x, and EnuCoor_i::y.
Referenced by moveWaypointForward().
uint8_t moveWaypointForward (uint8_t waypoint, float distanceMeters)
Definition at line 158 of file orange_avoider.c.
References calculateForwards(), and moveWaypoint().
Referenced by orange_avoider_periodic().
void orange_avoider_init (void)
Definition at line 68 of file orange_avoider.c.
References chooseRandomIncrementAvoidance(), color_cb_max, color_cb_min, color_cr_max, color_cr_min, color_lum_max, color_lum_min, ORANGE_AVOIDER_CB_MAX, ORANGE_AVOIDER_CB_MIN, ORANGE_AVOIDER_CR_MAX, ORANGE_AVOIDER_CR_MIN, ORANGE_AVOIDER_LUM_MAX, and ORANGE_AVOIDER_LUM_MIN.
void orange_avoider_periodic (void)
Definition at line 85 of file orange_avoider.c.
References chooseRandomIncrementAvoidance(), color_count, increase_nav_heading(), incrementForAvoidance, maxDistance, moveWaypointForward(), nav_heading, nav_set_heading_towards_waypoint(), safeToGoForwards, trajectoryConfidence, tresholdColorCount, VERBOSE_PRINT, and waypoint_set_here_2d().
Variable Documentation
float incrementForAvoidance
Definition at line 61 of file orange_avoider.c.
Referenced by chooseRandomIncrementAvoidance(), and orange_avoider_periodic().
uint8_t safeToGoForwards
Definition at line 59 of file orange_avoider.c.
Referenced by orange_avoider_periodic().
uint16_t trajectoryConfidence
Definition at line 62 of file orange_avoider.c.
Referenced by orange_avoider_periodic().