Paparazzi UAS: sw/airborne/modules/enose/anemotaxis.h File Reference
anemotaxis.h File Reference
#include "std.h"
Functions
bool nav_anemotaxis_downwind (uint8_t c, float radius)
bool nav_anemotaxis_init (uint8_t c)
bool nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Function Documentation
bool nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Not null even if wind_east=wind_north=0
Definition at line 42 of file anemotaxis.c.
References c1, c2, CARROT, chemo_sensor, CROSSWIND, DEFAULT_CIRCLE_RADIUS, last_plume, last_plume_was_here(), Max, nav_init_stage(), NavApproaching, NavCircleWaypoint, NavQdrCloseTo, NavSegment, sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), UTURN, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.
bool nav_anemotaxis_downwind (uint8_t c, float radius)
Definition at line 21 of file anemotaxis.c.
References stateGetHorizontalWindspeed_f(), waypoints, point::x, FloatVect2::x, point::y, and FloatVect2::y.
bool nav_anemotaxis_init (uint8_t c)
Definition at line 30 of file anemotaxis.c.
References DEFAULT_CIRCLE_RADIUS, last_plume_was_here(), sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), UTURN, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.