Paparazzi UAS: sw/airborne/modules/enose/anemotaxis.c File Reference
anemotaxis.c File Reference
#include "modules/enose/anemotaxis.h"
#include "generated/airframe.h"
#include "state.h"
#include "std.h"
#include "firmwares/fixedwing/nav.h"
#include "generated/flight_plan.h"
#include "subsystems/datalink/downlink.h"
#include "modules/enose/chemo_detect.h"
Enumerations
enum status { UTURN, CROSSWIND }
Functions
static void last_plume_was_here (void)
bool nav_anemotaxis_downwind (uint8_t c, float radius)
bool nav_anemotaxis_init (uint8_t c)
bool nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Variables
static enum status status
static int8_t sign
static struct point last_plume
Enumeration Type Documentation
enum status
Enumerator
UTURN
CROSSWIND
Definition at line 10 of file anemotaxis.c.
Function Documentation
static void last_plume_was_here (void) static
Definition at line 15 of file anemotaxis.c.
References last_plume, stateGetPositionEnu_f(), point::x, EnuCoor_f::x, point::y, and EnuCoor_f::y.
Referenced by nav_anemotaxis(), and nav_anemotaxis_init().
bool nav_anemotaxis (uint8_t c, uint8_t c1, uint8_t c2, uint8_t plume)
Not null even if wind_east=wind_north=0
Definition at line 42 of file anemotaxis.c.
References c1, c2, CARROT, chemo_sensor, CROSSWIND, DEFAULT_CIRCLE_RADIUS, last_plume, last_plume_was_here(), Max, nav_init_stage(), NavApproaching, NavCircleWaypoint, NavQdrCloseTo, NavSegment, sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), UTURN, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.
bool nav_anemotaxis_downwind (uint8_t c, float radius)
Definition at line 21 of file anemotaxis.c.
References stateGetHorizontalWindspeed_f(), waypoints, point::x, FloatVect2::x, point::y, and FloatVect2::y.
bool nav_anemotaxis_init (uint8_t c)
Definition at line 30 of file anemotaxis.c.
References DEFAULT_CIRCLE_RADIUS, last_plume_was_here(), sign, stateGetHorizontalWindspeed_f(), stateGetPositionEnu_f(), UTURN, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.
Variable Documentation
struct point last_plume static
Definition at line 13 of file anemotaxis.c.
Referenced by last_plume_was_here(), and nav_anemotaxis().
int8_t sign static
Definition at line 12 of file anemotaxis.c.
Referenced by nav_anemotaxis(), and nav_anemotaxis_init().
enum status status static
Definition at line 11 of file anemotaxis.c.