Paparazzi UAS: sw/airborne/modules/computer_vision/bebop_ae_awb.c File Reference
bebop_ae_awb.c File Reference
#include "bebop_ae_awb.h"
#include "boards/bebop.h"
#include "boards/bebop/mt9f002.h"
#include "lib/isp/libisp.h"
Macros
#define MAX_HIST_Y 255
#define sgn(x) (float)((x < 0) ? -1 : (x > 0))
#define BEBOP_AUTO_EXPOSURE true
#define BEBOP_AUTO_WHITE_BALANCE true
#define BEBOP_AWB_MIN_GAIN 2
#define BEBOP_AWB_MAX_GAIN 75
Functions
void bebop_ae_awb_init (void)
void bebop_ae_awb_periodic (void)
Detailed Description
Author
Freek van Tienen, Kirk Scheper Auto exposure and Auto white balancing for the Bebop 1 and 2
Definition in file bebop_ae_awb.c.
Macro Definition Documentation
#define BEBOP_AUTO_EXPOSURE true
Definition at line 36 of file bebop_ae_awb.c.
#define BEBOP_AUTO_WHITE_BALANCE true
Definition at line 40 of file bebop_ae_awb.c.
#define BEBOP_AWB_MAX_GAIN 75
Definition at line 44 of file bebop_ae_awb.c.
#define BEBOP_AWB_MIN_GAIN 2
Definition at line 43 of file bebop_ae_awb.c.
#define MAX_HIST_Y 255
Definition at line 31 of file bebop_ae_awb.c.
Referenced by bebop_ae_awb_periodic().
#define sgn (x) (float)((x < 0) ? -1 : (x > 0))
Definition at line 33 of file bebop_ae_awb.c.
Function Documentation
void bebop_ae_awb_init (void)
Definition at line 46 of file bebop_ae_awb.c.
void bebop_ae_awb_periodic (void)
Definition at line 48 of file bebop_ae_awb.c.
References isp_yuv_stats_t::ae_histogram_Y, isp_yuv_stats_t::awb_nb_grey_pixels, isp_yuv_stats_t::awb_sum_U, isp_yuv_stats_t::awb_sum_V, mt9f002_t::gain_blue, mt9f002_t::gain_red, isp_get_statistics_yuv(), MAX_HIST_Y, mt9f002, mt9f002_set_exposure(), mt9f002_set_gains(), isp_yuv_stats_t::nb_valid_Y, mt9f002_t::real_exposure, and mt9f002_t::target_exposure.