Paparazzi UAS: sw/airborne/modules/decawave/dw1000_arduino.h File Reference
dw1000_arduino.h File Reference
Functions
void dw1000_arduino_init (void)
void dw1000_arduino_periodic (void)
void dw1000_arduino_report (void)
void dw1000_arduino_event (void)
void dw1000_reset_heading_ref (void)
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
Detailed Description
Author
Gautier Hattenberger Driver to get ranging data from Decawave DW1000 modules connected to Arduino
Definition in file dw1000_arduino.h.
Function Documentation
void dw1000_arduino_event (void)
Definition at line 292 of file dw1000_arduino.c.
References DW1000::anchors, check_anchor_timeout(), dw1000, dw1000_arduino_parse(), DW1000::raw_pos, scale_position(), send_gps_dw1000_small(), trilateration_compute(), uart_char_available(), uart_getch(), and DW1000::updated.
void dw1000_arduino_init (void)
Definition at line 216 of file dw1000_arduino.c.
References LlaCoor_i::alt, DW1000::anchors, GpsState::cacc, DW1000::ck, GpsState::comp_id, Anchor::distance, dw1000, DW1000_INITIAL_HEADING, DW1000_NB_ANCHORS, DW_WAIT_STX, GpsState::fix, DW1000::gps_dw1000, GPS_DW1000_ID, GPS_FIX_NONE, Anchor::id, ids, DW1000::idx, DW1000::initial_heading, LlaCoor_i::lat, LlaCoor_i::lon, DW1000::ltp_def, ltp_def_from_lla_i(), GpsState::pacc, GpsState::pdop, Anchor::pos, DW1000::pos, pos_x, pos_y, pos_z, GpsState::sacc, DW1000::state, Anchor::time, trilateration_init(), DW1000::updated, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
void dw1000_arduino_periodic (void)
Definition at line 256 of file dw1000_arduino.c.
References dw1000, DW1000::gps_dw1000, and gps_periodic_check().
void dw1000_arduino_report (void)
Definition at line 262 of file dw1000_arduino.c.
References DW1000::anchors, DefaultChannel, DefaultDevice, Anchor::distance, dw1000, DW1000::pos, DW1000::raw_pos, EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
void dw1000_reset_heading_ref (void)
Reset reference heading to current heading AHRS/INS should be aligned before calling this function.
Definition at line 194 of file dw1000_arduino.c.
References dw1000, DW1000::initial_heading, FloatEulers::psi, and stateGetNedToBodyEulers_f().