Paparazzi UAS: International Standard Atmosphere utilities
International Standard Atmosphere utilities
Math
Macros
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
ISA sea level standard atmospheric pressure in Pascal.
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
ISA sea level standard temperature in Kelvin.
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
temperature laps rate in K/m
#define PPRZ_ISA_GRAVITY 9.80665
earth-surface gravitational acceleration in m/s^2
#define PPRZ_ISA_GAS_CONSTANT 8.31447
universal gas constant in J/(mol*K)
#define PPRZ_ISA_MOLAR_MASS 0.0289644
molar mass of dry air in kg/mol
#define PPRZ_ISA_AIR_GAS_CONSTANT (PPRZ_ISA_GAS_CONSTANT/PPRZ_ISA_MOLAR_MASS)
universal gas constant / molar mass of dry air in J*kg/K
#define PPRZ_ISA_AIR_DENSITY 1.225
standard air density in kg/m^3
Functions
static float pprz_isa_altitude_of_pressure (float pressure)
Get absolute altitude from pressure (using simplified equation).
static float pprz_isa_height_of_pressure (float pressure, float ref_p)
Get relative altitude from pressure (using simplified equation).
static float pprz_isa_pressure_of_altitude (float altitude)
Get pressure in Pa from absolute altitude (using simplified equation).
static float pprz_isa_pressure_of_height (float height, float ref_p)
Get pressure in Pa from height (using simplified equation).
static float pprz_isa_height_of_pressure_full (float pressure, float ref_p)
Get relative altitude from pressure (using full equation).
static float pprz_isa_ref_pressure_of_height_full (float pressure, float height)
Get reference pressure (QFE or QNH) from current pressure and height.
Variables
static const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT *PPRZ_ISA_SEA_LEVEL_TEMP / PPRZ_ISA_GRAVITY)
Detailed Description
Macro Definition Documentation
#define PPRZ_ISA_AIR_DENSITY 1.225
standard air density in kg/m^3
Definition at line 64 of file pprz_isa.h.
Referenced by eas_from_dynamic_pressure().
#define PPRZ_ISA_AIR_GAS_CONSTANT (PPRZ_ISA_GAS_CONSTANT/PPRZ_ISA_MOLAR_MASS)
universal gas constant / molar mass of dry air in J*kg/K
Definition at line 62 of file pprz_isa.h.
#define PPRZ_ISA_GAS_CONSTANT 8.31447
universal gas constant in J/(mol*K)
Definition at line 58 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_GRAVITY 9.80665
earth-surface gravitational acceleration in m/s^2
Definition at line 56 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_MOLAR_MASS 0.0289644
molar mass of dry air in kg/mol
Definition at line 60 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_SEA_LEVEL_PRESSURE 101325.0
ISA sea level standard atmospheric pressure in Pascal.
Definition at line 50 of file pprz_isa.h.
Referenced by get_tas_factor(), nps_fdm_init(), pprz_isa_altitude_of_pressure(), and pprz_isa_pressure_of_altitude().
#define PPRZ_ISA_SEA_LEVEL_TEMP 288.15
ISA sea level standard temperature in Kelvin.
Definition at line 52 of file pprz_isa.h.
Referenced by get_tas_factor(), pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
#define PPRZ_ISA_TEMP_LAPS_RATE 0.0065
temperature laps rate in K/m
Definition at line 54 of file pprz_isa.h.
Referenced by pprz_isa_height_of_pressure_full(), and pprz_isa_ref_pressure_of_height_full().
Function Documentation
static float pprz_isa_altitude_of_pressure (float pressure) inline static
Get absolute altitude from pressure (using simplified equation).
Referrence pressure is standard pressure at sea level
Parameters
pressure current pressure in Pascal (Pa)
Returns
altitude in m in ISA conditions
Definition at line 75 of file pprz_isa.h.
References PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_ms5611_event().
static float pprz_isa_height_of_pressure (float pressure, float ref_p) inline static
Get relative altitude from pressure (using simplified equation).
Given the current pressure and a reference pressure (at height=0), calculate the height above the reference in meters. If you pass QNH as reference pressure, you get the height above sea level. Using QFE as reference pressure, you get height above the airfield.
Parameters
pressure current pressure in Pascal (Pa)
ref_p reference pressure (QFE) when height=0 or QNH at sea level
Returns
height in m above reference in ISA conditions
Definition at line 95 of file pprz_isa.h.
Referenced by baro_cb(), ins_alt_float_update_baro(), and ins_float_invariant_update_baro().
static float pprz_isa_height_of_pressure_full (float pressure, float ref_p) inline static
Get relative altitude from pressure (using full equation).
Given the current pressure and a reference pressure (at height=0), calculate the height above the reference in meters. If you pass QNH as reference pressure, you get the height above sea level. Using QFE as reference pressure, you get height above the airfield.
Parameters
pressure current pressure in Pascal (Pa)
ref_p reference pressure (QFE or QNH) in Pa
Returns
height above reference in m in ISA conditions
Definition at line 139 of file pprz_isa.h.
References PPRZ_ISA_GAS_CONSTANT, PPRZ_ISA_GRAVITY, PPRZ_ISA_MOLAR_MASS, PPRZ_ISA_SEA_LEVEL_TEMP, and PPRZ_ISA_TEMP_LAPS_RATE.
Referenced by pressure_abs_cb().
static float pprz_isa_pressure_of_altitude (float altitude) inline static
Get pressure in Pa from absolute altitude (using simplified equation).
Parameters
altitude current absolute altitude in meters
Returns
static pressure in Pa at given altitude in ISA conditions
Definition at line 110 of file pprz_isa.h.
References PPRZ_ISA_SEA_LEVEL_PRESSURE.
Referenced by baro_sim_periodic(), and decode_gpspacket().
static float pprz_isa_pressure_of_height (float height, float ref_p) inline static
Get pressure in Pa from height (using simplified equation).
Parameters
height current height over reference (relative altitude) in meters
ref_p reference pressure (QFE or QNH) when height = 0
Returns
static pressure in Pa at given height in ISA conditions
Definition at line 122 of file pprz_isa.h.
static float pprz_isa_ref_pressure_of_height_full (float pressure, float height) inline static
Get reference pressure (QFE or QNH) from current pressure and height.
(using full equation)
Parameters
pressure current pressure in Pascal (Pa)
height height above referece (sea level for QNH, airfield alt for QFE) in m
Returns
reference pressure at height=0 in Pa
Definition at line 159 of file pprz_isa.h.
References PPRZ_ISA_GAS_CONSTANT, PPRZ_ISA_GRAVITY, PPRZ_ISA_MOLAR_MASS, PPRZ_ISA_SEA_LEVEL_TEMP, and PPRZ_ISA_TEMP_LAPS_RATE.
Referenced by pressure_abs_cb().
Variable Documentation
const float PPRZ_ISA_M_OF_P_CONST = (PPRZ_ISA_AIR_GAS_CONSTANT *PPRZ_ISA_SEA_LEVEL_TEMP / PPRZ_ISA_GRAVITY) static
Definition at line 66 of file pprz_isa.h.