Paparazzi UAS: sw/airborne/firmwares/rotorcraft/guidance/guidance_indi.h File Reference
guidance_indi.h File Reference
A guidance mode based on Incremental Nonlinear Dynamic Inversion Come to ICRA2016 to learn more!
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "math/pprz_algebra_float.h"
Functions
void guidance_indi_enter (void)
Call upon entering indi guidance.
void guidance_indi_run (bool in_flight, float heading_sp)
void stabilization_attitude_set_setpoint_rp_quat_f (struct FloatEulers *indi_rp_cmd, bool in_flight, float heading)
Variables
float guidance_indi_thrust_specific_force_gain
struct FloatVect3 euler_cmd
Detailed Description
A guidance mode based on Incremental Nonlinear Dynamic Inversion Come to ICRA2016 to learn more!
Definition in file guidance_indi.h.
Function Documentation
void guidance_indi_enter (void)
Call upon entering indi guidance.
Definition at line 109 of file guidance_indi.c.
References filter_cutoff, init_butterworth_2_low_pass(), FloatEulers::phi, stabilization_cmd, stateGetNedToBodyEulers_f(), FloatEulers::theta, thrust_act, and thrust_in.
Referenced by guidance_h_mode_changed().
void guidance_indi_run (bool in_flight, float heading_sp)
Parameters
in_flight in flight boolean
heading_sp the desired heading [rad]
main indi guidance function
Definition at line 129 of file guidance_indi.c.
References euler_cmd, Ga, Ga_inv, guidance_euler_cmd, guidance_h, GUIDANCE_H_MAX_BANK, guidance_indi_calcG(), guidance_indi_pos_gain, guidance_indi_propagate_filters(), guidance_indi_speed_gain, guidance_v_z_ref, MAT33_INV, MAT33_VECT3_MUL, SecondOrderLowPass::o, FloatEulers::phi, HorizontalGuidanceReference::pos, POS_FLOAT_OF_BFP, FloatEulers::psi, radio_control, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, HorizontalGuidance::ref, stabilization_attitude_set_setpoint_rp_quat_f(), stabilization_cmd, stateGetNedToBodyEulers_f(), stateGetPositionNed_f(), stateGetPositionNed_i(), stateGetSpeedNed_f(), FloatEulers::theta, thrust_in, THRUST_INCREMENT_ID, RadioControl::values, FloatVect3::x, NedCoor_f::x, Int32Vect2::x, FloatVect3::y, NedCoor_f::y, Int32Vect2::y, FloatVect3::z, and NedCoor_f::z.
Referenced by guidance_h_from_nav(), and guidance_h_guided_run().
void stabilization_attitude_set_setpoint_rp_quat_f (struct FloatEulers * indi_rp_cmd, bool in_flight, float heading)
Parameters
indi_rp_cmd roll/pitch command from indi guidance [rad] (float)
in_flight in flight boolean
heading the desired heading [rad] in BFP with INT32_ANGLE_FRAC
function that creates a quaternion from a roll, pitch and yaw setpoint
Definition at line 281 of file guidance_indi.c.
References float_quat_comp(), float_quat_comp_inv(), float_quat_comp_norm_shortest(), float_quat_normalize(), float_quat_of_axis_angle(), float_quat_of_eulers(), QUAT_BFP_OF_REAL, QUAT_COPY, stab_att_sp_quat, and stateGetNedToBodyEulers_f().
Referenced by guidance_indi_run().
Variable Documentation
struct FloatVect3 euler_cmd
Definition at line 95 of file guidance_indi.c.
Referenced by guidance_indi_run().
float guidance_indi_thrust_specific_force_gain