Paparazzi UAS: sw/airborne/modules/computer_vision/lib/filters/kalman_filter_vision.h File Reference
kalman_filter_vision.h File Reference
Functions
void kalman_filter_linear_2D_float (float *model, float *measurements, float *covariance, float *state, float *process_noise, float *measurement_noise)
A simple linear 2D kalman filter, computed using floats and matrices.
Function Documentation
void kalman_filter_linear_2D_float (float * model, float * measurements, float * covariance, float * state, float * process_noise, float * measurement_noise)
A simple linear 2D kalman filter, computed using floats and matrices.
To be used for vision task like optical flow, tracking markers etc.
Parameters
[in] *model The process model for the prediction of the next state (array size of [1 x 4])
[in] *measurements Values of the measurements (array size of [1 x 2])
[in] *covariance Covariance matrix of previous iteration (array size of [1 x 4])
[out] *covariance Updated Covariance matrix (array size of [1 x 4])
[in] *state Previous state vector with estimates(array size of [1 x 2])
[out] *state Updated state vector with estimates
[in] *measurement_noise Expected variance of the noise of the measurements
[in] *process_noise Expected variance of the noise of the process model
Definition at line 26 of file kalman_filter_vision.c.
References float_mat_copy(), float_mat_diff(), float_mat_mul(), float_mat_sum(), float_mat_transpose(), H, MAKE_MATRIX_PTR, Q, and mesonh.mesonh_atmosphere::Z.
Referenced by kalman_filter_opticflow_velocity().