Paparazzi UAS: sw/airborne/boards/bebop/mt9v117.h File Reference
mt9v117.h File Reference
Initialization and configuration of the MT9V117 CMOS Chip.
#include "std.h"
#include "mcu_periph/i2c.h"
Data Structures
struct mt9v117_t
Functions
void mt9v117_init (struct mt9v117_t *mt)
Initialisation of the Aptina MT9V117 CMOS sensor (1/6 inch VGA, bottom camera)
Detailed Description
Initialization and configuration of the MT9V117 CMOS Chip.
Definition in file mt9v117.h.
Data Structure Documentation
struct mt9v117_t
Definition at line 33 of file mt9v117.h.
Data Fields
struct i2c_periph * i2c_periph I2C peripheral used to communicate over.
struct i2c_transaction i2c_trans I2C transaction for comminication with CMOS chip.
Function Documentation
void mt9v117_init (struct mt9v117_t * mt)
Initialisation of the Aptina MT9V117 CMOS sensor (1/6 inch VGA, bottom camera)
Definition at line 363 of file mt9v117.c.
References mt9v117_t::i2c_trans, I2CTransDone, MT9V117_AE_RULE_ALGO_AVERAGE, MT9V117_AE_RULE_ALGO_OFFSET, MT9V117_AE_RULE_VAR, MT9V117_AWB_PIXEL_THRESHOLD_COUNT_OFFSET, MT9V117_AWB_VAR, MT9V117_CAM_CTRL_VAR, MT9V117_CAM_OUTPUT_FORMAT_BT656_ENABLE, MT9V117_CAM_OUTPUT_FORMAT_OFFSET, MT9V117_CHIP_ID, MT9V117_CHIP_ID_RESP, MT9V117_COMMAND, MT9V117_COMMAND_OK, MT9V117_COMMAND_SET_STATE, mt9v117_config(), MT9V117_PAD_SLEW, MT9V117_RESET_MISC_CTRL, MT9V117_RESET_SOC_I2C, MT9V117_SYS_STATE_ENTER_CONFIG_CHANGE, MT9V117_SYSMGR_NEXT_STATE_OFFSET, MT9V117_SYSMGR_VAR, mt9v117_write_patch(), read_reg(), read_var(), i2c_transaction::status, write_reg(), and write_var().
Referenced by board_init2().