Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main_ap.h File Reference
main_ap.h File Reference
Rotorcraft main loop.
Functions
void main_init (void)
Main initialization.
void main_event (void)
void handle_periodic_tasks (void)
void main_periodic (void)
void telemetry_periodic (void)
void failsafe_check (void)
Detailed Description
Rotorcraft main loop.
Definition in file main_ap.h.
Function Documentation
void failsafe_check (void)
Definition at line 287 of file main_ap.c.
References AP_MODE_FAILSAFE, AP_MODE_FLIP, AP_MODE_GUIDED, AP_MODE_HOME, AP_MODE_KILL, AP_MODE_MODULE, AP_MODE_NAV, autopilot_check_in_flight(), autopilot_get_mode(), autopilot_get_motors_on(), autopilot_set_mode(), Electrical::bat_critical, electrical, GpsIsLost, radio_control, RC_LOST_MODE, RC_OK, RC_REALLY_LOST, and RadioControl::status.
Referenced by handle_periodic_tasks(), and main_init().
void handle_periodic_tasks (void)
Definition at line 200 of file main_ap.c.
void main_event (void) inline
Definition at line 329 of file main_ap.c.
void main_init (void) inline
Main initialization.
Definition at line 116 of file main_ap.c.
void main_periodic (void) inline
Definition at line 235 of file main_ap.c.
void telemetry_periodic (void)
Definition at line 263 of file main_ap.c.