Paparazzi UAS: sw/airborne/subsystems/radio_control/spektrum.h File Reference
spektrum.h File Reference
Radio control spektrum interface.
#include "subsystems/radio_control/spektrum_arch.h"
Macros
#define RadioControlEvent(_received_frame_handler) RadioControlEventImp(_received_frame_handler)
Functions
void radio_control_spektrum_try_bind (void)
Detailed Description
Radio control spektrum interface.
Definition in file spektrum.h.
Macro Definition Documentation
#define RadioControlEvent (_received_frame_handler) RadioControlEventImp(_received_frame_handler)
Definition at line 36 of file spektrum.h.
Function Documentation
void radio_control_spektrum_try_bind (void)
Definition at line 42 of file spektrum_arch.c.
References gpio_clear(), gpio_get(), gpio_set(), gpio_setup_input(), gpio_setup_input_pulldown(), gpio_setup_input_pullup(), gpio_setup_output(), MASTER_RECEIVER_PULSES, SLAVE_RECEIVER_PULSES, SPEKTRUM_BIND_PIN, SPEKTRUM_BIND_PIN_PORT, SPEKTRUM_PRIMARY_BIND_CONF_PIN, SPEKTRUM_PRIMARY_BIND_CONF_PORT, SPEKTRUM_SECONDARY_BIND_CONF_PIN, SPEKTRUM_SECONDARY_BIND_CONF_PORT, and sys_time_usleep().