Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.c File Reference
stabilization_attitude_rc_setpoint.c File Reference
Read an attitude setpoint from the RC.
#include "firmwares/rotorcraft/stabilization/stabilization_attitude_rc_setpoint.h"
#include "generated/airframe.h"
#include "subsystems/radio_control.h"
#include "state.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
#include "firmwares/rotorcraft/autopilot_rc_helpers.h"
#include "mcu_periph/sys_time.h"
Macros
#define STABILIZATION_ATTITUDE_DEADBAND_A 0
#define STABILIZATION_ATTITUDE_DEADBAND_E 0
#define COORDINATED_TURN_AIRSPEED 12.0
Airspeed that will be used in the turning speed calculation (m/s).
#define YAW_DEADBAND_EXCEEDED()
Functions
static int32_t get_rc_roll (void)
static int32_t get_rc_pitch (void)
static int32_t get_rc_yaw (void)
static float get_rc_roll_f (void)
static float get_rc_pitch_f (void)
static float get_rc_yaw_f (void)
void stabilization_attitude_reset_care_free_heading (void)
reset the heading for care-free mode to current heading
int32_t stabilization_attitude_get_heading_i (void)
float stabilization_attitude_get_heading_f (void)
void stabilization_attitude_read_rc_setpoint_eulers (struct Int32Eulers *sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Read attitude setpoint from RC as euler angles.
void stabilization_attitude_read_rc_setpoint_eulers_f (struct FloatEulers *sp, bool in_flight, bool in_carefree, bool coordinated_turn)
void stabilization_attitude_read_rc_roll_pitch_quat_f (struct FloatQuat *q)
Read roll/pitch command from RC as quaternion.
void stabilization_attitude_read_rc_roll_pitch_earth_quat_f (struct FloatQuat *q)
Read roll/pitch command from RC as quaternion.
void stabilization_attitude_read_rc_setpoint_quat_f (struct FloatQuat *q_sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Read attitude setpoint from RC as quaternion Interprets the stick positions as axes.
void stabilization_attitude_read_rc_setpoint_quat_earth_bound_f (struct FloatQuat *q_sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Variables
float care_free_heading = 0
Detailed Description
Read an attitude setpoint from the RC.
Definition in file stabilization_attitude_rc_setpoint.c.
Macro Definition Documentation
#define COORDINATED_TURN_AIRSPEED 12.0
Airspeed that will be used in the turning speed calculation (m/s).
This variable is for calculation of the turn speed, and does not influence the airspeed. With a higher speed, the vehicle will turn less in a turn with the same roll.
Definition at line 51 of file stabilization_attitude_rc_setpoint.c.
Referenced by stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_read_rc_setpoint_eulers_f().
#define STABILIZATION_ATTITUDE_DEADBAND_A 0
Definition at line 37 of file stabilization_attitude_rc_setpoint.c.
Referenced by get_rc_roll(), and get_rc_roll_f().
#define STABILIZATION_ATTITUDE_DEADBAND_E 0
Definition at line 41 of file stabilization_attitude_rc_setpoint.c.
Referenced by get_rc_pitch(), and get_rc_pitch_f().
#define YAW_DEADBAND_EXCEEDED ()
Value:
(radio_control.values[RADIO_YAW] >  STABILIZATION_ATTITUDE_DEADBAND_R || \
   radio_control.values[RADIO_YAW] < -STABILIZATION_ATTITUDE_DEADBAND_R)
Definition at line 54 of file stabilization_attitude_rc_setpoint.c.
Referenced by stabilization_attitude_read_rc_setpoint_eulers(), and stabilization_attitude_read_rc_setpoint_eulers_f().
Function Documentation
static int32_t get_rc_pitch (void) static
Definition at line 73 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_BFP_OF_REAL, MAX_PPRZ, radio_control, RADIO_PITCH, STABILIZATION_ATTITUDE_DEADBAND_E, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_setpoint_eulers().
static float get_rc_pitch_f (void) static
Definition at line 104 of file stabilization_attitude_rc_setpoint.c.
References MAX_PPRZ, radio_control, RADIO_PITCH, STABILIZATION_ATTITUDE_DEADBAND_E, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_roll_pitch_earth_quat_f(), stabilization_attitude_read_rc_roll_pitch_quat_f(), and stabilization_attitude_read_rc_setpoint_eulers_f().
static int32_t get_rc_roll (void) static
Definition at line 61 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_BFP_OF_REAL, MAX_PPRZ, radio_control, RADIO_ROLL, STABILIZATION_ATTITUDE_DEADBAND_A, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_setpoint_eulers().
static float get_rc_roll_f (void) static
Definition at line 93 of file stabilization_attitude_rc_setpoint.c.
References MAX_PPRZ, radio_control, RADIO_ROLL, STABILIZATION_ATTITUDE_DEADBAND_A, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_roll_pitch_earth_quat_f(), stabilization_attitude_read_rc_roll_pitch_quat_f(), and stabilization_attitude_read_rc_setpoint_eulers_f().
static int32_t get_rc_yaw (void) static
Definition at line 85 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_BFP_OF_REAL, MAX_PPRZ, radio_control, RADIO_YAW, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_setpoint_eulers().
static float get_rc_yaw_f (void) inline static
Definition at line 115 of file stabilization_attitude_rc_setpoint.c.
References MAX_PPRZ, radio_control, RADIO_YAW, and RadioControl::values.
Referenced by stabilization_attitude_read_rc_setpoint_eulers_f().
float stabilization_attitude_get_heading_f (void)
Definition at line 150 of file stabilization_attitude_rc_setpoint.c.
References heading, FloatEulers::phi, FloatEulers::psi, stateGetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by stabilization_attitude_enter(), stabilization_attitude_read_rc_setpoint_eulers_f(), and stabilization_attitude_set_failsafe_setpoint().
int32_t stabilization_attitude_get_heading_i (void)
Definition at line 131 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_FLOAT_OF_BFP, heading, INT32_ANGLE_PI_2, INT32_TRIG_FRAC, INT_MULT_RSHIFT, Int32Eulers::phi, PPRZ_ITRIG_SIN, Int32Eulers::psi, stateGetNedToBodyEulers_i(), and Int32Eulers::theta.
Referenced by guidance_flip_enter(), stabilization_attitude_enter(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_set_failsafe_setpoint(), stabilization_indi_enter(), and stabilization_indi_set_failsafe_setpoint().
void stabilization_attitude_read_rc_roll_pitch_earth_quat_f (struct FloatQuat * q)
Read roll/pitch command from RC as quaternion.
Both angles are are interpreted relative to to the horizontal plane (earth bound).
Parameters
[out] q quaternion representing the RC roll/pitch input
Definition at line 348 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_FLOAT_OF_BFP, get_rc_pitch_f(), get_rc_roll_f(), FloatQuat::qi, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, and transition_theta_offset.
Referenced by stabilization_attitude_read_rc_setpoint_quat_earth_bound_f().
void stabilization_attitude_read_rc_roll_pitch_quat_f (struct FloatQuat * q)
Read roll/pitch command from RC as quaternion.
Interprets the stick positions as axes.
Parameters
[out] q quaternion representing the RC roll/pitch input
Definition at line 332 of file stabilization_attitude_rc_setpoint.c.
References float_quat_of_orientation_vect(), get_rc_pitch_f(), get_rc_roll_f(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stabilization_attitude_read_rc_setpoint_quat_f().
void stabilization_attitude_read_rc_setpoint_eulers (struct Int32Eulers * sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Read attitude setpoint from RC as euler angles.
Parameters
[in] coordinated_turn true if in horizontal mode forward
[in] in_carefree true if in carefree mode
[in] in_flight true if in flight
[out] sp attitude setpoint as euler angles
Definition at line 174 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_BFP_OF_REAL, ANGLE_FLOAT_OF_BFP, care_free_heading, COORDINATED_TURN_AIRSPEED, get_rc_pitch(), get_rc_roll(), get_rc_yaw(), get_sys_time_float(), heading, INT32_ANGLE_FRAC, INT32_ANGLE_NORMALIZE, INT_MULT_RSHIFT, last_ts, Int32Eulers::phi, PPRZ_ITRIG_COS, PPRZ_ITRIG_SIN, Int32Eulers::psi, stabilization_attitude_get_heading_i(), stateGetNedToBodyEulers_i(), Int32Eulers::theta, THROTTLE_STICK_DOWN, and YAW_DEADBAND_EXCEEDED.
Referenced by stabilization_attitude_read_rc(), stabilization_attitude_read_rc_setpoint_quat_earth_bound_f(), and stabilization_attitude_read_rc_setpoint_quat_f().
void stabilization_attitude_read_rc_setpoint_eulers_f (struct FloatEulers * sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Definition at line 253 of file stabilization_attitude_rc_setpoint.c.
References care_free_heading, COORDINATED_TURN_AIRSPEED, FLOAT_ANGLE_NORMALIZE, get_rc_pitch_f(), get_rc_roll_f(), get_rc_yaw_f(), get_sys_time_float(), heading, last_ts, FloatEulers::phi, FloatEulers::psi, stabilization_attitude_get_heading_f(), stateGetNedToBodyEulers_f(), FloatEulers::theta, THROTTLE_STICK_DOWN, and YAW_DEADBAND_EXCEEDED.
Referenced by guidance_h_read_rc(), stabilization_attitude_read_rc(), stabilization_attitude_read_rc_setpoint_quat_earth_bound_f(), and stabilization_attitude_read_rc_setpoint_quat_f().
void stabilization_attitude_read_rc_setpoint_quat_earth_bound_f (struct FloatQuat * q_sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Definition at line 428 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_FLOAT_OF_BFP, float_quat_comp(), float_quat_normalize(), float_quat_of_axis_angle(), FloatEulers::psi, QUAT_COPY, stab_att_sp_euler, stabilization_attitude_read_rc_roll_pitch_earth_quat_f(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_read_rc_setpoint_eulers_f(), and stateGetNedToBodyEulers_f().
Referenced by stabilization_attitude_read_rc(), and stabilization_indi_read_rc().
void stabilization_attitude_read_rc_setpoint_quat_f (struct FloatQuat * q_sp, bool in_flight, bool in_carefree, bool coordinated_turn)
Read attitude setpoint from RC as quaternion Interprets the stick positions as axes.
Parameters
[in] coordinated_turn true if in horizontal mode forward
[in] in_carefree true if in carefree mode
[in] in_flight true if in flight
[out] q_sp attitude setpoint as quaternion
Definition at line 375 of file stabilization_attitude_rc_setpoint.c.
References ANGLE_FLOAT_OF_BFP, care_free_heading, float_quat_comp(), float_quat_comp_inv(), float_quat_comp_norm_shortest(), float_quat_normalize(), float_quat_of_axis_angle(), FloatEulers::psi, QUAT_COPY, stab_att_sp_euler, stabilization_attitude_read_rc_roll_pitch_quat_f(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_read_rc_setpoint_eulers_f(), and stateGetNedToBodyEulers_f().
Referenced by stabilization_attitude_read_rc(), and stabilization_indi_read_rc().
void stabilization_attitude_reset_care_free_heading (void)
reset the heading for care-free mode to current heading
Definition at line 123 of file stabilization_attitude_rc_setpoint.c.
References care_free_heading, FloatEulers::psi, and stateGetNedToBodyEulers_f().
Referenced by guidance_h_mode_changed().
Variable Documentation
float care_free_heading = 0
Definition at line 58 of file stabilization_attitude_rc_setpoint.c.
Referenced by stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_read_rc_setpoint_eulers_f(), stabilization_attitude_read_rc_setpoint_quat_f(), and stabilization_attitude_reset_care_free_heading().