Paparazzi UAS: sw/airborne/arch/stm32/subsystems/radio_control/spektrum_arch.h File Reference
spektrum_arch.h File Reference
Macros
#define SPEKTRUM_NB_CHANNEL 12
#define RADIO_CONTROL_NB_CHANNEL 12
#define RADIO_THROTTLE 0
#define RADIO_ROLL 1
#define RADIO_PITCH 2
#define RADIO_YAW 3
#define RADIO_GEAR 4
#define RADIO_FLAP 5
#define RADIO_AUX1 5
#define RADIO_AUX2 6
#define RADIO_AUX3 7
#define RADIO_AUX4 8
#define RADIO_AUX5 9
#define RADIO_AUX6 10
#define RADIO_AUX7 11
#define RADIO_CONTROL_SPEKTRUM_SIGNS {1,1,1,1,1,1,1,1,1,1,1,1}
#define RADIO_MODE RADIO_GEAR
Functions
void RadioControlEventImp (void(*_received_frame_handler)(void))
void SpektrumUartInit (void)
Macro Definition Documentation
#define RADIO_AUX1 5
Definition at line 61 of file spektrum_arch.h.
#define RADIO_AUX2 6
Definition at line 62 of file spektrum_arch.h.
#define RADIO_AUX3 7
Definition at line 63 of file spektrum_arch.h.
#define RADIO_AUX4 8
Definition at line 64 of file spektrum_arch.h.
#define RADIO_AUX5 9
Definition at line 65 of file spektrum_arch.h.
#define RADIO_AUX6 10
Definition at line 66 of file spektrum_arch.h.
#define RADIO_AUX7 11
Definition at line 67 of file spektrum_arch.h.
#define RADIO_CONTROL_NB_CHANNEL 12
Definition at line 35 of file spektrum_arch.h.
#define RADIO_CONTROL_SPEKTRUM_SIGNS {1,1,1,1,1,1,1,1,1,1,1,1}
Definition at line 75 of file spektrum_arch.h.
#define RADIO_FLAP 5
Definition at line 59 of file spektrum_arch.h.
#define RADIO_GEAR 4
Definition at line 56 of file spektrum_arch.h.
#define RADIO_MODE RADIO_GEAR
Definition at line 82 of file spektrum_arch.h.
#define RADIO_PITCH 2
Definition at line 50 of file spektrum_arch.h.
#define RADIO_ROLL 1
Definition at line 47 of file spektrum_arch.h.
#define RADIO_THROTTLE 0
Definition at line 44 of file spektrum_arch.h.
#define RADIO_YAW 3
Definition at line 53 of file spektrum_arch.h.
#define SPEKTRUM_NB_CHANNEL 12
Definition at line 32 of file spektrum_arch.h.
Referenced by RadioControlEventImp().
Function Documentation
void RadioControlEventImp (void(*)(void) _received_frame_handler)
Definition at line 48 of file spektrum_arch.c.
References SpektrumStateStruct::ChannelCnt, ExpectedFrames, RadioControl::frame_cpt, SpektrumStateStruct::LostFrameCnt, MAX_PPRZ, Min, radio_control, RADIO_CONTROL_NB_CHANNEL, RADIO_THROTTLE, RC_OK, SpektrumStateStruct::RcAvailable, spektrum_available, SPEKTRUM_CHANNELS_PER_FRAME, SPEKTRUM_NB_CHANNEL, RadioControl::status, RadioControl::time_since_last_frame, RadioControl::values, and SpektrumStateStruct::values.
void SpektrumUartInit (void)
Definition at line 620 of file spektrum_arch.c.
References B115200, FALSE, gpio_enable_clock(), gpio_setup_pin_af(), NVIC_PRIMARY_UART_PRIO, PrimaryUart, and SecondaryUart.
Referenced by radio_control_impl_init(), received_spektrum_soft_bind(), and send_spektrum_bind().